#!/usr/bin/bash
#
# Put customizations to your image in this file.

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Exit if any commands fail
set -o errexit

# UniFi Controller Version
UNIFI_VERSION="5.0.7"
UNIFI_HASH="eb437c52d9fda7a584d09a520d43d1a9"

echo "* Add UniFi user"
useradd -d /opt/local/UniFi -s /usr/bin/false unifi

echo "* Download and install UniFi Controller Software"
wget http://dl.ubnt.com/unifi/${UNIFI_VERSION}/UniFi.unix.zip -O /tmp/UniFi.unix.zip
LOCAL_HASH=($(md5sum /tmp/UniFi.unix.zip))

if [[ "${UNIFI_HASH}" != "${LOCAL_HASH}" ]]; then
	echo "ERROR: You maybe downloaded the wrong file for UniFi.unix.zip"
	exit 1
fi

echo "* Extract to /opt/local"
unzip /tmp/UniFi.unix.zip -d /opt/local/UniFi

echo "* Use local installed mongodb binary"
ln -sf /opt/local/bin/mongod /opt/local/UniFi/bin/mongod

echo "* Provide own snappy java files, warning this mix versions"
mv /tmp/snappy-java-1.1.2.4.jar /opt/local/UniFi/lib/snappy-java-1.0.5.jar

echo "* Chown everything to the unify user"
chown -R unify:other /opt/local/UniFi

# Clean up
echo "* Cleaning up."
rm -rf /root/*

# Prepare image for provisioning
sm-prepare-image -y
