#!/usr/bin/bash
#
# Put customizations to your image in this file.

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# UniFi Controller Version
UNIFI_VERSION="5.7.23"
UNIFI_HASH="33e1cda0836ce170c731cc03da3e6e97"

# Exit if any commands fail
set -o errexit

echo "* Add UniFi user"
useradd -d /opt/local/UniFi -s /usr/bin/false unifi

echo "* Download and install UniFi Controller Software"
wget http://dl.ubnt.com/unifi/${UNIFI_VERSION}/UniFi.unix.zip -O /tmp/UniFi.unix.zip
LOCAL_HASH=($(md5sum /tmp/UniFi.unix.zip))

if [[ "${UNIFI_HASH}" != "${LOCAL_HASH}" ]]; then
	echo "ERROR: You maybe downloaded the wrong file for UniFi.unix.zip"
	exit 1
fi

echo "* Extract to /opt/local"
unzip /tmp/UniFi.unix.zip -d /opt/local/

echo "* Use local installed mongodb binary"
ln -sf /opt/local/bin/mongod /opt/local/UniFi/bin/mongod

echo "* Chown everything to the unify user"
chown -R unifi:other /opt/local/UniFi

echo "* Create ssl folder"
mkdir -p /opt/local/etc/nginx/ssl

echo "* Cleanup home/admin because of delegate dataset usage"
rm -rf /home/admin/.[^.]*

echo "* Cleaning up"
rm -rf /root/*

# Provide workaround for /.zonecontrol/metadata.sock issue
# https://github.com/joyent/smtools/issues/3
gsed -i 's:^rm -f /.zonecontrol/metadata.sock$:rm -f /.zonecontrol/metadata.sock || true:g' \
/opt/local/bin/sm-prepare-image

sm-prepare-image -y
